export const DummyData = [
  {
    id: 1,
    name: 'Stick Golf',
    photo: 'ada lah',
    sellPrice: 100000,
    buyPrice: 23287,
    stockLeft: 8229,
  },
  {
    id: 2,
    name: 'Panci',
    photo: 'ada lah',
    sellPrice: 29364,
    buyPrice: 900000,
    stockLeft: 34,
  },
  {
    id: 3,
    name: 'Map',
    photo: 'ada lah',
    sellPrice: 23124,
    buyPrice: 456,
    stockLeft: 34,
  },
  {
    id: 4,
    name: 'Map',
    photo: 'ada lah',
    sellPrice: 23124,
    buyPrice: 456,
    stockLeft: 34,
  },
  {
    id: 5,
    name: 'Map',
    photo: 'ada lah',
    sellPrice: 23124,
    buyPrice: 456,
    stockLeft: 34,
  },
  {
    id: 6,
    name: 'Map',
    photo: 'ada lah',
    sellPrice: 23124,
    buyPrice: 456,
    stockLeft: 34,
  },
  {
    id: 7,
    name: 'Map',
    photo: 'ada lah',
    sellPrice: 23124,
    buyPrice: 456,
    stockLeft: 34,
  },
  {
    id: 8,
    name: 'Map',
    photo: 'ada lah',
    sellPrice: 23124,
    buyPrice: 456,
    stockLeft: 34,
  },
  {
    id: 9,
    name: 'Map',
    photo: 'ada lah',
    sellPrice: 23124,
    buyPrice: 456,
    stockLeft: 34,
  },
  {
    id: 10,
    name: 'Map',
    photo: 'ada lah',
    sellPrice: 23124,
    buyPrice: 456,
    stockLeft: 34,
  },
  {
    id: 11,
    name: 'Map',
    photo: 'ada lah',
    sellPrice: 23124,
    buyPrice: 456,
    stockLeft: 34,
  },
];
